sudo: false

language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"

env:
  global:
    - AWS_REGION=us-east-1
    - SLS_DEBUG=true

before_install:
  - npm install -g serverless

script:
  - commitlint-travis
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] ; then ./scripts/deploy.sh ; fi'
