sudo: false

language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "node_modules"
    - $HOME/.mongodb-binaries # For mongodb-memory-server

env:
  global:
    - AWS_REGION=us-east-1
    - SLS_DEBUG=true

before_install:
  - npm install -g serverless

script:
  - npm run test-ci # Running inband is recommended for CI see https://github.com/facebook/jest/issues/3765
  - commitlint-travis
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] ; then ./scripts/deploy.sh ; fi'
