sudo: false

language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - "node_modules"
    - $HOME/.mongodb-binaries # For mongodb-memory-server

env:
  global:
    - AWS_REGION=us-east-1
    - SLS_DEBUG=true

before_install:
  - yarn global add serverless
  - export PATH=$(yarn global dir)/node_modules/.bin:$PATH

script:
  - yarn lint
  - yarn test-ci # Running inband is recommended for CI see https://github.com/facebook/jest/issues/3765
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "true" ] ; then commitlint-travis ; fi'
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] ; then ./scripts/deploy.sh ; fi'

notifications:
  webhooks:
    urls:
      - ${GITTER_WEBHOOK}
      - https://0323326e.ngrok.io/post
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
